### PR TITLE
Merge feature branch "Development" with develop branch

### PR DESCRIPTION
**Pull request by Greg0109**
IMPORTANT: This branch is called development as a mistake. It was not following gitflow but now it is. This branch is going to be merge with the develop branch

Changelog:
- Added all requested methods
- Used yield and call
- Added tests within the code for ease of testing

### CODE REVIEW

**Review by ebeagusamuel — CHANGES_REQUESTED** [review]
# Invalid Submission :red_circle: 
##### I will be marking this as invalid because of the wrong git-flow. You are expected to work with the right Git Flow: production master branch + main development branch + Pull Requests from feature branches to the develop.
slack(@ebeagusamuel)

**Comment by Greg0109** [comment]
Updated branches to follow gitflow method. This "development" branch is the feature branch that will be merged with the "Develop" branch

**Comment by Greg0109** [comment]
I accidentally closed the pull request, my bad, everything should be fixed now.

Updated branches to follow gitflow method. This "development" branch is the feature branch that will be merged with the "Develop" branch

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
#  **Changes Required 🛑♻**

<hr>

Hello Team, good job you've done so far on this project. However, there are still some issues you need to work on in order to get this PR approved 😊🙏

- [x] ```puts [1,2,3,4,5].my_select { |num| num.even? }``` logs out 2, 4, 5 and it should logs out 2, 4. Kindly fix this method
- [x] my_all, my_none, my_any methods don't accept the following as arguments:- 1. REGEX i.e. ```puts %w[ant bear cat].my_all?(/t/)``` logs out an error. 2. Classes i.e. ```puts [1, 3.14, 42].my_all?(Numeric)``` logs out the same error. Please fix those methods in order to accept these as arguments and test them using given examples  or examples of your own
- [x] my_all, my_none, my_any methods raise an error when no block is given, kindly fix this issue for those three methods
- [x] my_count method doesn't accept arguments i.e. ```puts ary.my_count(2)``` raises an error, instead it should log out 2
- [x] please fix my_map method in order to accept Ranges. i.e. ```puts (1..4).my_map{|i| i*i}``` raises an error
- [x] Your my_inject method doesn't accept Ranges, please fix it too

<hr>

Kindly make sure to fix all the above issues and re-submit for another review
Good luck and happy coding 👨‍💻💻

**Comment by Greg0109** [comment]
Required changes have been done. The first required change, the one said that my_select with num.even? didn't work was wrong, it does work with the given example

**Review by NtwaliHeritier — CHANGES_REQUESTED** [review]
### STATUS: CHANGES REQUIRED🛑
Hello team,
Great job on making the requested, however here are some tips.
As suggested by the previous TSE, when creating a review branch or a branch to work on, avoid using names like development, since the development or develop name is booked for the base branch in git flow. next time use more meaningful branch names, specifying what you implemented in the feature.

Here are the requested changes
[REQUESTED] my_each, my_select should return an enumerator when no block is given.
[REQUESTED] array.my_each(&block) should  equal array.each(&block)
[REQUESTED] array.my_select(&block) should  equal array.select(&block)
[REQUESTED] array.my_none? has to be true
[REQUESTED] array.my_inject(:+) should equal to array.inject(:+)

Kindly fix these errors to ask for another review

**Comment by sergiocortessat** [comment]
Required changes have been applied.

**Comment by Greg0109** [comment]
> ### STATUS: CHANGES REQUIRED🛑
> Hello team,
> Great job on making the requested, however here are some tips.
> As suggested by the previous TSE, when creating a review branch or a branch to work on, avoid using names like development, since the development or develop name is booked for the base branch in git flow. next time use more meaningful branch names, specifying what you implemented in the feature.
> 
> Here are the requested changes
> [REQUESTED] my_each, my_select should return an enumerator when no block is given.
> [REQUESTED] array.my_each(&block) should equal array.each(&block)
> [REQUESTED] array.my_select(&block) should equal array.select(&block)
> [REQUESTED] array.my_none? has to be true
> [REQUESTED] array.my_inject(:+) should equal to array.inject(:+)
> 
> Kindly fix these errors to ask for another review

The branch was named "Development" as a mistake. As you can see, this PR is to merge Development with develop, with is the second main branch following the git flow structure.

**Review by arslanbisharat — APPROVED** [review]
# Approved :smile: 

Hello Developer :wave:

I just reviewed your project, and I am thrilled to inform you that your project is approved.
Congratulations on achieving this milestone in your career. :clap:

_I am looking forward to seeing your next project._

Stay safe and give me a smile 😇

### Happy Coding
------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

**Comment by Greg0109** [comment]
Thanks for your review Arsian!

**Pull request merged**
